---
- name: This play is used to create ec2 instance using SG and tasgs
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
  - name: create ec2 instance
    ec2:
      instance_type: t2.micro
      image: ami-009110a2bf8d7dd0a
      count: 1
      key_name: control_key
      region: ap-south-1
      wait: yes
      group_id: ['sg-0b4e48810130b1d86','sg-5cd41330']
      instance_tags: 
        Name: Ubuntu_Server
        Server: Ubuntu_Node1
        